[build]
  publish = "build"  # Adjust this to match your build output directory
  command = "npm run build"  # Your project's build command

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200